# Include strict rules from package
# include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    # Strict type safety configuration:
    strict-casts: true # Disallows implicit type casts (e.g. from dynamic)
    strict-inference: true # Disallows inferring dynamic when type is not explicitly specified
    strict-raw-types: true # Requires type arguments for generic types (e.g. List<String> instead of List)

  errors:
    # Elevate critical warnings to compilation errors
    missing_return: error
    dead_code: error
    always_declare_return_types: error

    # Ignored warnings
    todo: ignore
    deprecated_member_use: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    # Custom rule overrides:
    public_member_api_docs: false

